require_once(__DIR__.'/../vendor/hh_autoload.php');

use \Facebook\HackRouter\Codegen;
use \HackFacebook\UiServer\Controllers\RoutableController;
use namespace Facebook\{HackCodegen as hcg, TypeAssert};
final class UpdateCodegen {
    public function main(): void {
        \printf("\nBuilding Router-related codegen...");
        Codegen::forTree(
            __DIR__.'/../src/controllers/',
            shape(
                'controllerBase' => RoutableController::class,
                'router' => shape(
                        'abstract' => true,
                        'file' => __DIR__.'/../src/RequestRouter/AutoGeneratedRouterBase.php',
                        'class' => 'AutoGeneratedRouterBase',
                    )
                ),
        )->build();
    }
}


<<__EntryPoint>>
async function main(): Awaitable<noreturn> {
    $codegen = new UpdateCodegen();
    $codegen->main();
    exit(0);
}
