<?hh // strict
/**
 * This file is generated. Do not modify it manually!
 *
 * To re-generate this file run
 * /Users/abhikmitra/personalProjects/facebook-hack/ui-server/scripts/build_router.hack
 *
 *
 * @generated SignedSource<<35cad858eed19cf7c2f82b71ddff00fb>>
 */

abstract class AutoGeneratedRouterBase
  extends \Facebook\HackRouter\BaseRouter<classname<\HackFacebook\UiServer\Controllers\IRoutableController>> {

  <<__Override>>
  final public function getRoutes(
  ): ImmMap<\Facebook\HackRouter\HttpMethod, ImmMap<string, classname<\HackFacebook\UiServer\Controllers\IRoutableController>>> {
    $map = ImmMap {
      \Facebook\HackRouter\HttpMethod::GET => ImmMap {
        '/' => \HackFacebook\UiServer\Controllers\Pages\HomePageController::class,
        '/login' =>
          \HackFacebook\UiServer\Controllers\Pages\LoginPageController::class,
        '/signUp' =>
          \HackFacebook\UiServer\Controllers\Pages\SignUpPageController::class,
      },
      \Facebook\HackRouter\HttpMethod::POST => ImmMap {
        '/login' =>
          \HackFacebook\UiServer\Controllers\API\LoginPostController::class,
        '/signUp' =>
          \HackFacebook\UiServer\Controllers\API\SignUpPostController::class,
      },
    };
    return $map;
  }
}
