namespace HackFacebook\UiServer\RequestRouter;

use \HackFacebook\UiServer\GlobalValues;
use \HackFacebook\UiServer\Controllers\{WebController, NotFoundController};
use Facebook\HackRouter\{HttpMethod, NotFoundException};

class FBRouter extends \AutoGeneratedRouterBase{

}
